// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:363


#include "ExampleInterfacesC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "ExampleInterfacesC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// .\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_cs.cpp:51

// Traits specializations for ExampleInterfaces::IAdder.

ExampleInterfaces::IAdder_ptr
TAO::Objref_Traits<ExampleInterfaces::IAdder>::duplicate (
    ExampleInterfaces::IAdder_ptr p)
{
  return ExampleInterfaces::IAdder::_duplicate (p);
}

void
TAO::Objref_Traits<ExampleInterfaces::IAdder>::release (
    ExampleInterfaces::IAdder_ptr p)
{
  ::CORBA::release (p);
}

ExampleInterfaces::IAdder_ptr
TAO::Objref_Traits<ExampleInterfaces::IAdder>::nil (void)
{
  return ExampleInterfaces::IAdder::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ExampleInterfaces::IAdder>::marshal (
    const ExampleInterfaces::IAdder_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*ExampleInterfaces__TAO_IAdder_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj) = 0;

// TAO_IDL - Generated from
// d:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

::CORBA::Double
ExampleInterfaces::IAdder::add (::CORBA::Double arg1,
::CORBA::Double arg2)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_IAdder_Proxy_Broker_ == 0)
    {
      ExampleInterfaces_IAdder_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Double>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_arg1 (arg1);
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_arg2 (arg2);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_arg1,
      &_tao_arg2
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "add",
      3,
      this->the_TAO_IAdder_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

ExampleInterfaces::IAdder::IAdder (void)
 : the_TAO_IAdder_Proxy_Broker_ (0)
{
  this->ExampleInterfaces_IAdder_setup_collocation ();
}

void
ExampleInterfaces::IAdder::ExampleInterfaces_IAdder_setup_collocation ()
{
  if (::ExampleInterfaces__TAO_IAdder_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_IAdder_Proxy_Broker_ =
        ::ExampleInterfaces__TAO_IAdder_Proxy_Broker_Factory_function_pointer (this);
    }
}

ExampleInterfaces::IAdder::~IAdder (void)
{}

void 
ExampleInterfaces::IAdder::_tao_any_destructor (void *_tao_void_pointer)
{
  IAdder *_tao_tmp_pointer =
    static_cast<IAdder *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

ExampleInterfaces::IAdder_ptr
ExampleInterfaces::IAdder::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<IAdder>::narrow (
        _tao_objref,
        "IDL:SLB/ExampleInterfaces/IAdder:1.0",
        ExampleInterfaces__TAO_IAdder_Proxy_Broker_Factory_function_pointer
      );
}

ExampleInterfaces::IAdder_ptr
ExampleInterfaces::IAdder::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<IAdder>::unchecked_narrow (
        _tao_objref,
        "IDL:SLB/ExampleInterfaces/IAdder:1.0",
        ExampleInterfaces__TAO_IAdder_Proxy_Broker_Factory_function_pointer
      );
}

ExampleInterfaces::IAdder_ptr
ExampleInterfaces::IAdder::_nil (void)
{
  return 0;
}

ExampleInterfaces::IAdder_ptr
ExampleInterfaces::IAdder::_duplicate (IAdder_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
ExampleInterfaces::IAdder::_tao_release (IAdder_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ExampleInterfaces::IAdder::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:SLB/ExampleInterfaces/IAdder:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* ExampleInterfaces::IAdder::_interface_repository_id (void) const
{
  return "IDL:SLB/ExampleInterfaces/IAdder:1.0";
}

::CORBA::Boolean
ExampleInterfaces::IAdder::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// d:\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/objref_typecode.cpp:70

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_ExampleInterfaces_IAdder (
    ::CORBA::tk_objref,
    "IDL:SLB/ExampleInterfaces/IAdder:1.0",
    "IAdder");
  

namespace ExampleInterfaces
{
  ::CORBA::TypeCode_ptr const _tc_IAdder =
    &_tao_tc_ExampleInterfaces_IAdder;
}

// TAO_IDL - Generated from
// d:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/any_op_cs.cpp:46
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<ExampleInterfaces::IAdder>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace ExampleInterfaces
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      IAdder_ptr _tao_elem)
  {
    IAdder_ptr _tao_objptr =
      IAdder::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      IAdder_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<IAdder>::insert (
        _tao_any,
        IAdder::_tao_any_destructor,
        _tc_IAdder,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      IAdder_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<IAdder>::extract (
          _tao_any,
          IAdder::_tao_any_destructor,
          _tc_IAdder,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ExampleInterfaces::IAdder_ptr _tao_elem)
{
  ExampleInterfaces::IAdder_ptr _tao_objptr =
    ExampleInterfaces::IAdder::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ExampleInterfaces::IAdder_ptr *_tao_elem)
{
  TAO::Any_Impl_T<ExampleInterfaces::IAdder>::insert (
      _tao_any,
      ExampleInterfaces::IAdder::_tao_any_destructor,
      ExampleInterfaces::_tc_IAdder,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    ExampleInterfaces::IAdder_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<ExampleInterfaces::IAdder>::extract (
        _tao_any,
        ExampleInterfaces::IAdder::_tao_any_destructor,
        ExampleInterfaces::_tc_IAdder,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// d:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/cdr_op_cs.cpp:53

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const ExampleInterfaces::IAdder_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    ExampleInterfaces::IAdder_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::ExampleInterfaces::IAdder RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        ExampleInterfaces__TAO_IAdder_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



