// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// .\be\be_codegen.cpp:859

#ifndef EXAMPLEINTERFACESI_H_
#define EXAMPLEINTERFACESI_H_

#include "ExampleInterfacesS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  ExampleInterfaces_IAdder_i
  : public virtual POA_ExampleInterfaces::IAdder
{
public:
  // Constructor 
  ExampleInterfaces_IAdder_i (void);
  
  // Destructor 
  virtual ~ExampleInterfaces_IAdder_i (void);
  
  virtual
  CORBA::Double add (
      ::CORBA::Double arg1,
      ::CORBA::Double arg2
    );
//     ACE_THROW_SPEC ((
//       CORBA::SystemException
//     ));
};


#endif /* EXAMPLEINTERFACESI_H_  */

