// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// .\be\be_codegen.cpp:859

#ifndef NSLISTERI_H_
#define NSLISTERI_H_

#include "nslisterS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  TaoTester_IExampleZero_i
  : public virtual POA_TaoTester::IExampleZero
{
public:
  // Constructor 
  TaoTester_IExampleZero_i (void);
  
  // Destructor 
  virtual ~TaoTester_IExampleZero_i (void);
  
  virtual
  void SetString (
      const char * inString
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
};


#endif /* NSLISTERI_H_  */

