//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
[System.Xml.Serialization.XmlRootAttribute("net", Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN", IsNullable=false)]
public partial class eDSPNNet : NetType {
    
    private PlaceType[] placeField;
    
    private ExponentialTransitionType[] exponentialTransitionField;
    
    private ImmediateTransitionType[] immediateTransitionField;
    
    private DeterministicTransitionType[] deterministicTransitionField;
    
    private GeneralTransitionType[] generalTransitionField;
    
    private ArcType[] arcField;
    
    private InhibitType[] inhibitField;
    
    private MeasureType[] measureField;
    
    private DefinitionType[] definitionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("place")]
    public PlaceType[] place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("exponentialTransition")]
    public ExponentialTransitionType[] exponentialTransition {
        get {
            return this.exponentialTransitionField;
        }
        set {
            this.exponentialTransitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("immediateTransition")]
    public ImmediateTransitionType[] immediateTransition {
        get {
            return this.immediateTransitionField;
        }
        set {
            this.immediateTransitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("deterministicTransition")]
    public DeterministicTransitionType[] deterministicTransition {
        get {
            return this.deterministicTransitionField;
        }
        set {
            this.deterministicTransitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("generalTransition")]
    public GeneralTransitionType[] generalTransition {
        get {
            return this.generalTransitionField;
        }
        set {
            this.generalTransitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("arc")]
    public ArcType[] arc {
        get {
            return this.arcField;
        }
        set {
            this.arcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("inhibit")]
    public InhibitType[] inhibit {
        get {
            return this.inhibitField;
        }
        set {
            this.inhibitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("measure")]
    public MeasureType[] measure {
        get {
            return this.measureField;
        }
        set {
            this.measureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("definition")]
    public DefinitionType[] definition {
        get {
            return this.definitionField;
        }
        set {
            this.definitionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class PlaceType : NodeType {
    
    private LabelType labelField;
    
    private string initialMarkingField;
    
    public PlaceType() {
        this.initialMarkingField = "0";
    }
    
    /// <remarks/>
    public LabelType label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string initialMarking {
        get {
            return this.initialMarkingField;
        }
        set {
            this.initialMarkingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class LabelType : TextType {
    
    private string textField;
    
    public LabelType() {
        this.textField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DefinitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasureType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LabelType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class TextType {
    
    private GraphicsType graphicsField;
    
    private Type typeField;
    
    private string idField;
    
    public TextType() {
        this.typeField = Type.text;
    }
    
    /// <remarks/>
    public GraphicsType graphics {
        get {
            return this.graphicsField;
        }
        set {
            this.graphicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Type type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class GraphicsType {
    
    private string xField;
    
    private string yField;
    
    private string orientationField;
    
    public GraphicsType() {
        this.orientationField = "0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class HandleType {
    
    private GraphicsType graphicsField;
    
    private string idField;
    
    /// <remarks/>
    public GraphicsType graphics {
        get {
            return this.graphicsField;
        }
        set {
            this.graphicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InscriptionType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class InscriptionTextType {
    
    private GraphicsType graphicsField;
    
    private Type typeField;
    
    private string idField;
    
    public InscriptionTextType() {
        this.typeField = Type.inscriptionText;
    }
    
    /// <remarks/>
    public GraphicsType graphics {
        get {
            return this.graphicsField;
        }
        set {
            this.graphicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Type type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public enum Type {
    
    /// <remarks/>
    node,
    
    /// <remarks/>
    connector,
    
    /// <remarks/>
    text,
    
    /// <remarks/>
    inscriptionText,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class InscriptionType : InscriptionTextType {
    
    private string textField;
    
    public InscriptionType() {
        this.textField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InhibitType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class ConnectorType {
    
    private string fromNodeField;
    
    private string toNodeField;
    
    private string idField;
    
    private Type typeField;
    
    public ConnectorType() {
        this.typeField = Type.connector;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fromNode {
        get {
            return this.fromNodeField;
        }
        set {
            this.fromNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string toNode {
        get {
            return this.toNodeField;
        }
        set {
            this.toNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Type type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class InhibitType : ConnectorType {
    
    private InscriptionType inscriptionField;
    
    private HandleType[] handleField;
    
    /// <remarks/>
    public InscriptionType inscription {
        get {
            return this.inscriptionField;
        }
        set {
            this.inscriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handle")]
    public HandleType[] handle {
        get {
            return this.handleField;
        }
        set {
            this.handleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class ArcType : ConnectorType {
    
    private InscriptionType inscriptionField;
    
    private HandleType[] handleField;
    
    /// <remarks/>
    public InscriptionType inscription {
        get {
            return this.inscriptionField;
        }
        set {
            this.inscriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("handle")]
    public HandleType[] handle {
        get {
            return this.handleField;
        }
        set {
            this.handleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class AddDataType {
    
    private string classnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string classname {
        get {
            return this.classnameField;
        }
        set {
            this.classnameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TransitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GeneralTransitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeterministicTransitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ImmediateTransitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExponentialTransitionType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class NodeType {
    
    private GraphicsType graphicsField;
    
    private string idField;
    
    private Type typeField;
    
    public NodeType() {
        this.typeField = Type.node;
    }
    
    /// <remarks/>
    public GraphicsType graphics {
        get {
            return this.graphicsField;
        }
        set {
            this.graphicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Type type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GeneralTransitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeterministicTransitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ImmediateTransitionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExponentialTransitionType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class TransitionType : NodeType {
    
    private LabelType labelField;
    
    /// <remarks/>
    public LabelType label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class GeneralTransitionType : TransitionType {
    
    private string delayField;
    
    private PreemptionPolicyType preemptionPolicyField;
    
    public GeneralTransitionType() {
        this.delayField = "1.0";
        this.preemptionPolicyField = PreemptionPolicyType.PRD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.0")]
    public string delay {
        get {
            return this.delayField;
        }
        set {
            this.delayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PreemptionPolicyType.PRD)]
    public PreemptionPolicyType preemptionPolicy {
        get {
            return this.preemptionPolicyField;
        }
        set {
            this.preemptionPolicyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public enum PreemptionPolicyType {
    
    /// <remarks/>
    PRD,
    
    /// <remarks/>
    PRS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class DeterministicTransitionType : TransitionType {
    
    private string delayField;
    
    private PreemptionPolicyType preemptionPolicyField;
    
    private string dTSPNpriorityField;
    
    public DeterministicTransitionType() {
        this.delayField = "1.0";
        this.preemptionPolicyField = PreemptionPolicyType.PRD;
        this.dTSPNpriorityField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.0")]
    public string delay {
        get {
            return this.delayField;
        }
        set {
            this.delayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PreemptionPolicyType.PRD)]
    public PreemptionPolicyType preemptionPolicy {
        get {
            return this.preemptionPolicyField;
        }
        set {
            this.preemptionPolicyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string DTSPNpriority {
        get {
            return this.dTSPNpriorityField;
        }
        set {
            this.dTSPNpriorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class ImmediateTransitionType : TransitionType {
    
    private string priorityField;
    
    private string weightField;
    
    private string enablingFunctionField;
    
    public ImmediateTransitionType() {
        this.priorityField = "1";
        this.weightField = "1";
        this.enablingFunctionField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string enablingFunction {
        get {
            return this.enablingFunctionField;
        }
        set {
            this.enablingFunctionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class ExponentialTransitionType : TransitionType {
    
    private string delayField;
    
    private ServerTypeType serverTypeField;
    
    private PreemptionPolicyType preemptionPolicyField;
    
    private string dTSPNpriorityField;
    
    public ExponentialTransitionType() {
        this.delayField = "1.0";
        this.serverTypeField = ServerTypeType.ExclusiveServer;
        this.preemptionPolicyField = PreemptionPolicyType.PRD;
        this.dTSPNpriorityField = "1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.0")]
    public string delay {
        get {
            return this.delayField;
        }
        set {
            this.delayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ServerTypeType.ExclusiveServer)]
    public ServerTypeType serverType {
        get {
            return this.serverTypeField;
        }
        set {
            this.serverTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PreemptionPolicyType.PRD)]
    public PreemptionPolicyType preemptionPolicy {
        get {
            return this.preemptionPolicyField;
        }
        set {
            this.preemptionPolicyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string DTSPNpriority {
        get {
            return this.dTSPNpriorityField;
        }
        set {
            this.dTSPNpriorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public enum ServerTypeType {
    
    /// <remarks/>
    InfiniteServer,
    
    /// <remarks/>
    ExclusiveServer,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(eDSPNNet))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class NetType {
    
    private string idField;
    
    private string netclassField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string netclass {
        get {
            return this.netclassField;
        }
        set {
            this.netclassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class DefinitionType : TextType {
    
    private AddDataType additionalDataField;
    
    private DefTypeType defTypeField;
    
    private string nameField;
    
    private string expressionField;
    
    public DefinitionType() {
        this.defTypeField = DefTypeType.@int;
    }
    
    /// <remarks/>
    public AddDataType additionalData {
        get {
            return this.additionalDataField;
        }
        set {
            this.additionalDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DefTypeType.@int)]
    public DefTypeType defType {
        get {
            return this.defTypeField;
        }
        set {
            this.defTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string expression {
        get {
            return this.expressionField;
        }
        set {
            this.expressionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public enum DefTypeType {
    
    /// <remarks/>
    @int,
    
    /// <remarks/>
    real,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pdv.cs.tu-berlin.de/TimeNET/schema/eDSPN")]
public partial class MeasureType : TextType {
    
    private AddDataType additionalDataField;
    
    private string nameField;
    
    private string expressionField;
    
    private string resultField;
    
    public MeasureType() {
        this.resultField = "";
    }
    
    /// <remarks/>
    public AddDataType additionalData {
        get {
            return this.additionalDataField;
        }
        set {
            this.additionalDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string expression {
        get {
            return this.expressionField;
        }
        set {
            this.expressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}
